# Generated by Django 4.2.1 on 2024-07-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('clave1', models.CharField(max_length=254)),
                ('clave2', models.CharField(max_length=254)),
            ],
        ),
    ]
