# Generated by Django 5.0.6 on 2024-05-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
