# Generated by Django 4.2.1 on 2024-04-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='cotizacion',
        ),
        migrations.DeleteModel(
            name='Cotizaciones',
        ),
    ]
