# Generated by Django 5.0.6 on 2024-06-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='fecha_Creacion',
        ),
    ]
