# Generated by Django 5.0.6 on 2024-05-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='foto',
            field=models.ImageField(default='fotos_servicios/servicio.jpg', upload_to='fotos_servicios/'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='precio',
            field=models.IntegerField(default=100000),
        ),
    ]
