# Generated by Django 4.2 on 2024-03-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_usuarios_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='foto',
        ),
    ]
