# Generated by Django 5.0.6 on 2024-05-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_usuarios_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.IntegerField(blank=True),
        ),
    ]
