# Generated by Django 5.0.6 on 2024-08-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_detallefactura_precio_alter_detallefactura_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
