# Generated by Django 4.2.1 on 2024-04-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_citas_cotizacion_delete_cotizaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiculo', models.CharField(max_length=254, null=True)),
                ('modelo', models.IntegerField(default=1900)),
                ('kilometraje', models.IntegerField(default=1236456)),
                ('placa', models.CharField(max_length=6, null=True)),
                ('linea', models.CharField(max_length=254, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.clientes')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.empleado')),
                ('servicio', models.ForeignKey(default='Mantenimiento', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.servicios')),
            ],
        ),
        migrations.AddField(
            model_name='citas',
            name='cotizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.cotizaciones'),
        ),
    ]
