# Generated by Django 5.0.6 on 2024-05-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_servicios_foto_servicios_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='foto',
            field=models.ImageField(default='fotos_usuarios/user.png', upload_to='fotos_productos/'),
        ),
    ]
