# Generated by Django 5.0.6 on 2024-06-26 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_detallefactura_cita_detallefactura_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='foto',
        ),
    ]
