# Generated by Django 4.2 on 2024-03-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_usuarios_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(default='fotos_usuarios/user.png', upload_to='fotos_usuarios/'),
        ),
    ]
