# Generated by Django 5.0.6 on 2024-05-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_usuarios_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='fecha_contratacion',
        ),
    ]
