# Generated by Django 4.2.1 on 2024-04-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_cotizaciones_citas_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.usuarios'),
        ),
    ]
