# Generated by Django 5.0.6 on 2024-07-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_productos_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='producto',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.FileField(default='media/user.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='producto',
            field=models.ManyToManyField(to='tienda.productos'),
        ),
    ]
