# Generated by Django 4.2 on 2024-01-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_remove_calificaciones_idcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='Precio',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='servicios',
            name='nombre',
            field=models.CharField(max_length=254),
        ),
    ]
