# Generated by Django 4.2 on 2024-01-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_servicios_precio_remove_servicios_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='tipoServicio',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=254),
        ),
    ]
