# Generated by Django 5.0.6 on 2024-07-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_detallefactura_producto_alter_usuarios_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(default='media/user.png', upload_to='media/'),
        ),
    ]
