# Generated by Django 4.2 on 2024-03-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_calificaciones_nombre_calificaciones_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.usuarios'),
        ),
    ]
