# Generated by Django 4.2 on 2024-01-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_remove_productos_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='idCliente',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='idEmpleado',
        ),
        migrations.AddField(
            model_name='citas',
            name='empleado',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='citas',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
