# Generated by Django 5.0.6 on 2024-05-22 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_usuarios_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='servicios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.servicios'),
        ),
    ]
