# Generated by Django 5.0.6 on 2024-05-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_calificaciones_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='n',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
