# Generated by Django 4.2 on 2024-03-30 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_alter_calificaciones_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='tipoServicio',
        ),
        migrations.AddField(
            model_name='citas',
            name='cliente',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.usuarios'),
        ),
        migrations.AddField(
            model_name='citas',
            name='cotizacion',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.cotizaciones'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='empleado',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.empleado'),
        ),
    ]
