# Generated by Django 5.0.6 on 2024-08-02 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_detallesservicio_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesservicio',
            name='producto',
        ),
        migrations.AddField(
            model_name='detallesservicio',
            name='producto',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.productos'),
        ),
    ]
