# Generated by Django 4.2 on 2024-01-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_citas_idcliente_remove_citas_idempleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='foto',
            field=models.ImageField(default='fotos_productos/default.png', upload_to='fotos_productos/'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='tipoServicio',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
