# Generated by Django 5.0.6 on 2024-05-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_usuarios_n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesservicio',
            name='producto',
        ),
        migrations.AddField(
            model_name='detallesservicio',
            name='producto',
            field=models.ManyToManyField(to='tienda.productos'),
        ),
    ]
