# Generated by Django 4.2 on 2024-03-30 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_remove_citas_tiposervicio_citas_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.usuarios'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='cotizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.cotizaciones'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.empleado'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.clientes'),
        ),
    ]
