# Generated by Django 4.2 on 2024-03-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_citas_cliente_alter_citas_cotizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='empleado',
        ),
    ]
