# Generated by Django 5.0.6 on 2024-05-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_remove_detallesservicio_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesservicio',
            name='fecha',
        ),
        migrations.AddField(
            model_name='detallesservicio',
            name='descripcion_proceso',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
