# Generated by Django 4.2 on 2024-02-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_rename_descripcion_cotizaciones_vehiculo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='proveedor',
        ),
    ]
