# Generated by Django 4.2 on 2024-02-24 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_remove_productos_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Proveedores',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.proveedores'),
        ),
    ]
