# Generated by Django 4.2 on 2024-02-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_productos_proveedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='Proveedores',
        ),
    ]
