# Generated by Django 4.2 on 2024-03-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_citas_cliente_citas_cotizacion_citas_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='fechaServicio',
            field=models.DateField(null=True),
        ),
    ]
