# Generated by Django 4.2 on 2024-03-30 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_alter_citas_fechaservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='productos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.productos'),
        ),
    ]
