# Generated by Django 4.2 on 2024-02-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_remove_productos_proveedores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='citas',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='cotizaciones',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cotizaciones',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='cotizaciones',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='productos',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='nombre',
            field=models.CharField(default='anonimo', max_length=254),
        ),
        migrations.AddField(
            model_name='citas',
            name='tipoServicio',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='citas',
            name='empleado',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='empleado',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='servicio',
            field=models.CharField(max_length=254),
        ),
    ]
