# Generated by Django 4.2.1 on 2024-04-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_servicios_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
