# Generated by Django 4.2 on 2024-02-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0013_remove_calificaciones_cliente_remove_citas_cliente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedores',
        ),
    ]
