# Generated by Django 4.2.1 on 2024-04-12 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_alter_facturas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.usuarios'),
        ),
    ]
