# Generated by Django 4.2 on 2024-02-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_delete_proveedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('nit', models.IntegerField(unique=True)),
                ('telefono', models.IntegerField(unique=True)),
                ('correo', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detallesservicio',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
