# Generated by Django 4.2 on 2024-02-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_proveedores_remove_detallesservicio_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('Precio', models.IntegerField()),
                ('descripcion_producto', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('fecha_Creacion', models.DateField()),
                ('foto', models.ImageField(default='fotos_productos/stock.jpg', upload_to='fotos_productos/')),
            ],
        ),
        migrations.AddField(
            model_name='detallesservicio',
            name='producto',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.productos'),
        ),
    ]
