# Generated by Django 4.2.1 on 2024-04-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_alter_facturas_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='productos',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.productos'),
        ),
    ]
