# Generated by Django 4.2.1 on 2024-04-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_remove_detallefactura_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='n',
            field=models.IntegerField(default=0),
        ),
    ]
