# Generated by Django 4.2 on 2024-02-27 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_productos_detallesservicio_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.facturas'),
        ),
        migrations.AlterField(
            model_name='detallesservicio',
            name='producto',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.productos'),
        ),
        migrations.AlterField(
            model_name='detallesservicio',
            name='servicio',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.servicios'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='cliente',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.clientes'),
        ),
    ]
