# Generated by Django 4.2 on 2024-02-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0017_alter_detallefactura_factura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizaciones',
            old_name='servicio',
            new_name='servicios',
        ),
    ]
