# Generated by Django 4.2.1 on 2024-04-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_alter_clientes_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cedula',
            field=models.IntegerField(default=0),
        ),
    ]
