# Generated by Django 4.2 on 2024-02-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_rename_servicio_cotizaciones_servicios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizaciones',
            old_name='servicios',
            new_name='tipos',
        ),
    ]
