# Generated by Django 4.2 on 2024-03-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_rename_servicios_cotizaciones_tipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='nombre',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='cliente',
            field=models.ForeignKey(default='Anonimo', on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.clientes'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(default='fotos_productos/default.png', upload_to='fotos_productos/'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='clave',
            field=models.CharField(max_length=8),
        ),
    ]
