# Generated by Django 4.2 on 2024-03-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0021_alter_calificaciones_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='cliente',
        ),
    ]
