# Generated by Django 4.2 on 2024-03-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_remove_calificaciones_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='nombre',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tienda.categoria'),
        ),
    ]
