# Generated by Django 4.2 on 2024-03-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0023_calificaciones_nombre_productos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='nombre',
            field=models.CharField(default='0', max_length=254, null=True),
        ),
    ]
