# Generated by Django 4.2 on 2024-03-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0024_alter_calificaciones_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calificaciones',
        ),
    ]
